### ISSUE TITLE
Endpoint not displaying all the transactions

### ISSUE THREAD

**Issue by AndreaScorza** [ltonetwork/lto-public-chain#99] opened 2021-11-08 16:10 UTC
The endpoint ```/transactions/address/{address}/limit/{limit}``` should display all the transactions relevant to a specific address, but it doesn't show any ```Anchor``` transaction.

**Comment by jasny** [comment] 2021-11-18 12:06
Duplicate of #50

**Closed by jasny** 2021-11-18 12:06 UTC
Labels: bug
